### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by dmadhitama** [vkothapally/SkipConvNet#1]
Hello.

Is the pretrained model available so that I can test for dereverberate my own reverberated speech audio?

Thank you.

**Comment by vkothapally** [comment]
Hello,

Yes, there are a few updates to the decoding scripts. I will complete uploading all scripts and pretrained models by tomorrow. 

Thank you.

**Comment by dmadhitama** [comment]
Thank you for the respond, looking forward to it!

**Comment by vkothapally** [comment]
Hello,

I have uploaded the saved model and a demo file. You should be able to enhance your audio files using the demo script. I'm closing this for now, feel free to reopen it if you come across any difficulties running it.

Thank you.
