### ISSUE TITLE
Training using own dataset

### ISSUE THREAD

**Issue by dmadhitama** [vkothapally/SkipConvNet#2]
Hello again,

Thank you for the repo and your pre-trained model before. It worked very well in some of my own data.
However, I want to train the model with my own dataset. So hopefully the model perform better. How should I do to prepare my own dataset to train using this model?

FYI, there are some audio in my dataset, like: clean data (no reverb), real reverberated data, and room & microphone IR data. I imagined the prepared dataset was like speech separation using U-Net (clean data, noisy data, and noise data), isn't it the same?

**Comment by vkothapally** [comment]
This doesn't seem to be an issue about the repo, so I shall be closing this on GitHub. However, please reach out to me at vinay.kothapally@utdallas.edu. We can probably setup a short meeting to go over on how to use this on your data.
